### ISSUE TITLE
文件查找失败：'uview-ui/components/u-table-column/u-table-column.vue'

### ISSUE THREAD

**Issue by zonglinlee** [u-leo/umy-ui#10]
在uniapp中使用，请问一下，和uview-ui库冲突，组件找不到怎么解决啊，使用了uni-app的easycome

**Comment by livelyPeng** [comment]
不能再uniapp中使用哦，肯定冲突啊  都是u- 开头的组件！

**Comment by livelyPeng** [comment]
你可以使用 vue  写webapp  这样运行在h5中！
