### ISSUE TITLE
利用sortabe排序后,无法获得排序后的数组data

### ISSUE THREAD

**Issue by XuLongfei96** [u-leo/umy-ui#101]
el-table中，可以通过.$refs.elTable.tableData获取排序后的数组数据；
在u-table中，请问该通过哪个属性获取排序后的数组数据？

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/132443301-913f997b-8e2e-4bf1-a2fa-64ffb4e71be6.png)

**Comment by XuLongfei96** [comment]
好的，谢谢,通过this.$refs.elTable.tableExample().tableData可以获得界面渲染的data

**Comment by shoushangdetuolaji** [comment]
好像不行啊，`this.$refs.elTable.tableExample().tableData` 
显示出来是 data.length = 0

**Comment by XuLongfei96** [comment]
> 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0

我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题
![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png)
![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)

**Comment by shoushangdetuolaji** [comment]
![image](https://user-images.githubusercontent.com/37497536/142342739-1d2c8f98-d9ae-4413-9a6e-6e9057454804.png)
![image](https://user-images.githubusercontent.com/37497536/142342775-55f28533-40ee-4ed8-bc24-b4b7bf8f9d11.png)
![image](https://user-images.githubusercontent.com/37497536/142342812-f92e524f-c2a0-4e6e-9c79-c72bce28ee10.png)
是不是我定义`:data`不对

**Comment by shoushangdetuolaji** [comment]
> > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> 
> 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)



> > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> 
> 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)

可能前辈用的是u-table我用的是ux-grid。。。

**Comment by XuLongfei96** [comment]
> > > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> > 
> > 
> > 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)
> 
> > > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> > 
> > 
> > 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)
> 
> 可能前辈用的是u-table我用的是ux-grid。。。

有可能的，我用的是u-table，参数如下：
![image](https://user-images.githubusercontent.com/44487503/142343359-ca8ebf23-4aec-40b8-a101-950ac74b8913.png)

**Comment by shoushangdetuolaji** [comment]
> > > > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> > > 
> > > 
> > > 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)
> > 
> > 
> > > > 好像不行啊，`this.$refs.elTable.tableExample().tableData` 显示出来是 data.length = 0
> > > 
> > > 
> > > 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 ![image](https://user-images.githubusercontent.com/44487503/142341180-13c948e2-384f-4ef1-ae6e-1b56250a9ece.png) ![image](https://user-images.githubusercontent.com/44487503/142341201-d5566802-fdc0-409a-bfe2-ef6e48c2c97e.png)
> > 
> > 
> > 可能前辈用的是u-table我用的是ux-grid。。。
> 
> 有可能的，我用的是u-table，参数如下： ![image](https://user-images.githubusercontent.com/44487503/142343359-ca8ebf23-4aec-40b8-a101-950ac74b8913.png)

嗯嗯，感谢前辈及时回复，估计作者可以修修了的🤣

**Comment by livelyPeng** [comment]
先去打印tableExample&nbsp;this.$refs.elTable.tableExample()&nbsp; &nbsp;而不是着急去取值tableData&nbsp;。说不定 不是tableData&nbsp;字段呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 上午10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 利用sortabe排序后,无法获得排序后的数组data (#101)





    
好像不行啊，this.$refs.elTable.tableExample().tableData 显示出来是 data.length = 0
  
我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题  
    
好像不行啊，this.$refs.elTable.tableExample().tableData 显示出来是 data.length = 0
  
我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题  
  
可能前辈用的是u-table我用的是ux-grid。。。
  
有可能的，我用的是u-table，参数如下：
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shoushangdetuolaji** [comment]
> 先去打印tableExample&nbsp;this.$refs.elTable.tableExample()&nbsp; &nbsp;而不是着急去取值tableData&nbsp;。说不定 不是tableData&nbsp;字段呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月18日(星期四) 上午10:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [u-leo/umy-ui] 利用sortabe排序后,无法获得排序后的数组data (#101) 好像不行啊，this.$refs.elTable.tableExample().tableData 显示出来是 data.length = 0 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 好像不行啊，this.$refs.elTable.tableExample().tableData 显示出来是 data.length = 0 我又试了一次，是可以的；是不是ref写错了？我用的vue是2版本，你如果用vue3的话可能会有问题 可能前辈用的是u-table我用的是ux-grid。。。 有可能的，我用的是u-table，参数如下： — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

嗯 打印了`this.$refs.elTable.tableExample()` 确实有好多字段和实例函数, 有字段data 是原始排序数据，tableData是长度为0，用的是ux-grid组件，也查看文档对应的reloadData 是promise对象 但then出来的数据是undefined的😥

**Comment by shoushangdetuolaji** [comment]
## 已解决了
`ux-grid` 获取排序后的显示数据在
`this.$refs.plxTable.tableExample().getTableData().visibleData`

谢谢xulongfei96和livelyPeng的提示！☕☕
