### ISSUE TITLE
如果是自定义可排序显隐列，用了插槽 后表头顺序更新了，但是对应字段顺序没有更新，必须浏览器刷新才会重新渲染表格内数据

### ISSUE THREAD

**Issue by Wilburn-hub** [u-leo/umy-ui#103]
如果是自定义可排序显隐列，用了插槽 后表头名字顺序更新了，但是对应字段顺序没有更新，必须浏览器刷新才会重新渲染表格内数据，
![Mac_2021-09-10 上午1 48 29](https://user-images.githubusercontent.com/64264596/132736857-bc71ad15-c6a4-4192-b646-5f233353295a.png)
![Mac_2021-09-10 上午1 48 15](https://user-images.githubusercontent.com/64264596/132736864-d6129822-dea5-412f-a320-3cac399d3c10.png)
![Mac_2021-09-10 上午1 48 02](https://user-images.githubusercontent.com/64264596/132736868-5e460a04-0aa3-483c-b89c-d749bec13ceb.png)

**Comment by Wilburn-hub** [comment]
![Uploading Mac_2021-09-10 上午1.49.54.png…]()

**Comment by Wilburn-hub** [comment]
![Mac_2021-09-10 上午1 49 54](https://user-images.githubusercontent.com/64264596/132740963-9ae8c911-8253-4cc0-9658-394acfe1e155.png)

**Comment by Wilburn-hub** [comment]
![Mac_2021-09-10 上午2 20 43](https://user-images.githubusercontent.com/64264596/132741347-95408542-2fae-43ed-bc05-e678a59ee4ae.png)

**Comment by livelyPeng** [comment]
让表格重回 刷新下，看文档方法

**Comment by Wilburn-hub** [comment]
![Mac_2021-09-10 下午2 57 35](https://user-images.githubusercontent.com/64264596/132812957-624f54cb-656f-49d7-8622-c7fe3cad46a3.png)
是这几个刷新的方法吗，没有效果，因为我不用插槽时是没问题的，但是我用了插槽，并且是用v-if判断的，会不会是这个原因。
如果是用
![Mac_2021-09-10 下午3 06 26](https://user-images.githubusercontent.com/64264596/132813985-6e961d7d-eda1-4613-ae6d-d11fe355d8ea.png)
就会导致
![Mac_2021-09-10 下午3 06 48](https://user-images.githubusercontent.com/64264596/132814068-17510f8a-f984-4ab7-9e27-181a2209dfbd.png)
是不是方法不对

**Comment by Wilburn-hub** [comment]
还是说调用的地方不对

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/132819704-b022c993-180f-4314-a57a-361443a54b5f.png)
自己去找问题  我没时间跟你废话

**Comment by Wilburn-hub** [comment]
这个方法已经试过，也不行，看来只有曲线救国用。location.reload()
感谢分享

**Comment by Wilburn-hub** [comment]
找到不用刷新浏览器即可动态更新数据（之前可能是因为我用到虚拟表格 ，同时插槽用了v-if导致 表格数据无法和表头无法对应）
方法就是强制重新渲染组件。给组件v-if绑定一个变量，在监听表头 变化时 重新渲染表格，同时重新拉数据并绑定到表格。
![Mac_2021-09-10 下午11 38 58](https://user-images.githubusercontent.com/64264596/132880169-a40558c9-6c54-4e84-8e48-63ffa99ced54.png)
![Mac_2021-09-10 下午11 39 07](https://user-images.githubusercontent.com/64264596/132880179-1a040f36-3105-4684-97c0-60e047d20564.png)
![Mac_2021-09-10 下午11 39 22](https://user-images.githubusercontent.com/64264596/132880181-908623cc-204f-44d1-b209-93b0ec35e979.png)
希望对后面使用组件遇到相同问题的同学有参考帮助，感谢作者强大的组件
