### ISSUE TITLE
只有一行并且多个单元格校验不通过时，点击切换不同单元格，console出现报错信息

### ISSUE THREAD

**Issue by neilguangzhou** [u-leo/umy-ui#104]
现象：
使用官方api文档中的例子：http://www.umyui.com/umycomponent/tableRules/
删除第2和3行，剩下第1行数据。在名字和年龄单元格来回点击。控制台出现报错信息。
![image](https://user-images.githubusercontent.com/7279290/133384228-93fa76b3-b3fa-490b-9a6b-e1ffa69d50d7.png)

期望：对异常做处理。

**Comment by livelyPeng** [comment]
这个问题可以不管他，就是获取元素 top  等等节点信息 报错，因为 节点元素不存在，然后报错了， 里面缺少个判断！
