### ISSUE TITLE
ux-grid.css 会覆盖body的样式

### ISSUE THREAD

**Issue by Julyrainy** [u-leo/umy-ui#106]
根据文档，按需加载 ux-grid，会导致全局body的样式被覆盖，添加上了line-height: 1.5，请问为啥会去改 body 的样式，感觉有点奇怪，另外有啥好办法不让他这么覆盖吗。
`
import { UxGrid, UxTableColumn } from 'umy-ui';
export default {
    components: {
        UxGrid,
        UxTableColumn
    }
`

**Comment by livelyPeng** [comment]
你再说什么啊，听不懂 啥添加上了line-height: 1.5，请问为啥会去改 body 的样式 ？？？？ 完全懵逼！CSS都这么复杂吗

**Comment by Julyrainy** [comment]
不好意思，重新叙述一下。
按需加载ux-grid，
会自动引入一个 ux-grid.css，
这个css文件中，有以下的样式，
body {line-height: 1.5; }，
这个样式会覆盖我的全局body的样式。
我的问题是，为什么会这样，为什么ux-grid.css里会有修改 body 样式的代码。
