### ISSUE TITLE
ux-grid 更新数据后设置滚动条不回到顶部 多次出现数据与滚动条位置不对应,求帮助

### ISSUE THREAD

**Issue by Wilburn-hub** [u-leo/umy-ui#108]
![Mac_2021-09-27 下午7 49 14](https://user-images.githubusercontent.com/64264596/134902698-ee117a09-cf49-42f4-b818-c8bc9ae1169d.png)
![Mac_2021-09-27 下午7 53 01](https://user-images.githubusercontent.com/64264596/134902916-61f1b532-4ffa-49b5-bb18-759d70fb8b29.png)
用了  @table-body-scroll="scroll"
scroll({ scrollTop, scrollLeft }) {
      this.scrollTop = scrollTop
      this.scrollLeft = scrollLeft
    },

**Comment by Wilburn-hub** [comment]
![Mac_2021-09-27 下午10 12 23](https://user-images.githubusercontent.com/64264596/134925607-ff9cf800-95cf-4c98-b33e-2885712346a2.png)
放到nexttick 以后 还是会出现偶尔返回顶部，横向滚动条确没问题

**Comment by Wilburn-hub** [comment]
请作者大大帮帮忙看看

**Comment by livelyPeng** [comment]
setTimeout延迟滚动位置
