### ISSUE TITLE
insertRow方法，是否可以指定位置呢？目标版本1.1.6，无法使用指定位置插入，文档的意思是可以指定位置吗？

### ISSUE THREAD

**Issue by zds1** [u-leo/umy-ui#109]
文档属性说明如下:
![image](https://user-images.githubusercontent.com/48559773/135231707-11c2cd9e-9b11-484f-b399-a4ed625c7624.png)

代码如下:
![image](https://user-images.githubusercontent.com/48559773/135232301-06f61bd2-8647-4923-a7cf-01a892ef5bf1.png)

指定了位置，报错如下：
![image](https://user-images.githubusercontent.com/48559773/135232351-e0722c24-588b-4741-a888-c2dc8c3f59d2.png)

**Comment by livelyPeng** [comment]
// 添加插入行
           async insertEvent (row) {
            let record = {
                name: '李四',
               sex: 'nv',
               age: 18
            }
            // 加入行, 表示加入行的row对象，row为空则插入第一行，为-1插入最后一行
            let { row: newRow } = await this.$refs.plxTable.insertRow(record, row)
     第二个参数 是表格中的row， 是个对象，是表格数据， 不是一个  穿  1234  行排序，   能不能别问 弱鸡问题

**Comment by zds1** [comment]
源码在这里，insertRow(e,t)；其中e的类型为：obj，t的类型为：number，图中的bug这么明显

![image](https://user-images.githubusercontent.com/48559773/135491651-bd170177-eafc-4880-a1ea-b07b51389ec9.png)
提问题的原因是不解，作者不想求证，可以不回答当忽视；请不要回一段有问题的代码好吗？没测试过我能乱发提问吗？还是说对自己的代码很自信？这种搞it的态度，我都很难相信你是作者。做学术还是严谨一点的好。
