### ISSUE TITLE
使用u-table和sortablejs拖拽行数据，如果跨页拖拽，onEnd事件中获取的索引是错的

### ISSUE THREAD

**Issue by JoyTiann** [u-leo/umy-ui#110]
请问大佬，使用u-table和sortablejs拖拽行数据，如果跨页拖拽，onEnd事件中获取的索引是错的，这个有什么解决思路吗？

**Comment by livelyPeng** [comment]
这个就是sortablejs需要的知道的问题了。跟表格没关系！不知道跨页
