### ISSUE TITLE
为啥不能支持虚拟列的多表头呢？希望作者把这块加上

### ISSUE THREAD

**Issue by chaojimct** [u-leo/umy-ui#112]
可以表头不虚拟，只做数据的虚拟呀，速度也不会慢呀
我现在就是用了两个表格做的，第一个一个只有表头并且合并表头，第二个只有数据并关联第一个表的横向滚动

**Comment by chaojimct** [comment]
> 你这个问题 问得非常好。但是 如果表格本地去实现这个 多级头， 表体虚拟滚动，也跟你这个方式类似！

是这样的，所以如果可以的话，你们可以把这个功能加上，我这是没有办法的办法🤣🤣🤣🤣

**Comment by LeonardoHsia** [comment]
还是打算切回单表头 自己模拟作者的思路写虚拟表头。。。

**Comment by crow04** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
