### ISSUE TITLE
在vue eui的Dialog中报错Error in event handler for "click": "TypeError: this.$refs.sendListRef.openAlterDialog is not a function"

### ISSUE THREAD

**Issue by nanjunyu** [u-leo/umy-ui#116]
在vue eui的Dialog弹窗中报错Error in event handler for "click": "TypeError: this.$refs.sendListRef.openAlterDialog is not a function"

但是在普通的页面中同样的代码使用是正常的，用的是ux-grid，后端小白诚恳请教

main.js是这样引入的

import {
  UTableColumn,
  UTable,
  UxGrid,
  UxTableColumn
} from 'umy-ui';

Vue.use(UTableColumn);
Vue.use(UTable);
Vue.use(UxGrid);
Vue.use(UxTableColumn);

![image](https://user-images.githubusercontent.com/23097168/141404037-6c49b280-b0aa-468b-ad17-74edfcd2f565.png)

**Comment by livelyPeng** [comment]
给出复现链接，加群。给出demo!
