### ISSUE TITLE
handlePageSize无效怎么回事

### ISSUE THREAD

**Issue by tianxia0079** [u-leo/umy-ui#117]
我正在使用 umy-ui table.handlePageSize无效怎么回事

**Comment by livelyPeng** [comment]
给出复现链接

**Comment by tianxia0079** [comment]
cdn引入html的方式下；
复制http://www.umyui.com/umycomponent/tableWithPagination
这个链接里代码，界面点击页码，不触发handlePageSize方法。
    <u-table
                                :data="tableData"
                                :pagination-show="true"
                                :total="pageForm.total"
                                :page-size="pageForm.pageSize"
                                :current-page="pageForm.currentPage"
                                @handlePageSize.native="handlePageSize"
                                :max-height="height">
                            <u-table-column
                                    prop="name"
                                    label="名字"
                                    width="180">
                            </u-table-column>
                            <u-table-column
                                    prop="sex"
                                    label="性别"
                                    width="180">
                            </u-table-column>
                            <u-table-column
                                    prop="age"
                                    label="年龄">
                            </u-table-column>
                        </u-table>
