### ISSUE TITLE
ux-grid 不支持 partRowSelections 选择事件吗？大数据列表使用toggleRowSelection切换选择会很卡顿，期望增加partRowSelections。

### ISSUE THREAD

**Issue by Shuhuchuan** [u-leo/umy-ui#119]

**Comment by livelyPeng** [comment]
ux应该不会卡，可以给我复现吗

**Comment by mietlove** [comment]
@parlay96 这个问题可以重新打开吗，我遇到了

**Comment by crow04** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by parlay96** [comment]
@mietlove 加群 给个复现链接，我觉得ux不会卡

**Comment by mietlove** [comment]
> @mietlove 加群 给个复现链接，我觉得ux不会卡

我很早加过群了， 这是复现链接: https://codesandbox.io/p/sandbox/umy-ui-forked-g8nrzq?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C38
实际问题场景是，我自己实现了shift 多选，但是拖动滚动条后，会选择很多数据, 就会很卡
