### ISSUE TITLE
使用use-virtual并设置row-height后造成cell-style属性失效

### ISSUE THREAD

**Issue by 934556826** [u-leo/umy-ui#121]
使用use-virtual并设置row-height后，cellstyle属性定义的行单元格的 style无效。怀疑是动态渲染每次都会在行单元格的行内样式重写高度，造成cellstyle定义的不生效？

**Comment by 934556826** [comment]
cellStyle({ row, column, rowIndex, columnIndex }) {
      // 区别不同条件，返回的颜色值
      if(columnIndex === 0) {
        if(row.conditionId <= 0){
          return 'background-color:red'
        } else {
          return 'background-color:yellow'
        }
      }
}）
这是我的代码，原先是基于el-table写的，没有问题，使用u-table并设置use-virtual后就不行了

**Comment by livelyPeng** [comment]
是不生效 还是 样式没加上去呢？

**Comment by 934556826** [comment]
> 是不生效 还是 样式没加上去呢？

应该是样式没加上去，因为同样的代码，我删除use-virtual后就没问题

**Comment by livelyPeng** [comment]
使用row-style试试  row-class-name  不然 没办法了

**Comment by 934556826** [comment]
可以确实是BUG吗

**Comment by livelyPeng** [comment]
不确定哦

**Comment by livelyPeng** [comment]
可以给复现链接

**Comment by 934556826** [comment]
搞明白了，是不支持直接返回样式字符串 要以对象的方式返回

**Comment by livelyPeng** [comment]
那你不要删除这个问题，因为后面的人 会遇到！
