### ISSUE TITLE
tree-node 为true下，点击事件冒泡未阻止，与行点击事件冲突

### ISSUE THREAD

**Issue by CDUTgaohongfei** [u-leo/umy-ui#126]
tree-node 为true下，点击事件冒泡未阻止，与行点击事件冲突；具体为点击展开箭头时会触发行点击事件；需要阻止箭头上点击事件向外冒泡

**Comment by livelyPeng** [comment]
这个问题  自己不要搞点击行事件，可以点击单元格事件，判断下！
