### ISSUE TITLE
ux-grid树表格如何获取半选的节点数据

### ISSUE THREAD

**Issue by huochangying** [u-leo/umy-ui#128]
看了半天文档，没找到能抛出半选状态的方法

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/147022200-fb1a8836-4b1b-433e-a99f-9fcf1a882c0e.png)

**Comment by huochangying** [comment]
> ![image](https://user-images.githubusercontent.com/32978177/147022200-fb1a8836-4b1b-433e-a99f-9fcf1a882c0e.png)
不好意思 我试了下这个只能获取勾选状态的节点
我的场景是点击子节点的时候希望能获取到当前选中的子节点（1个）和半选状态的父节点（1个）一共两条数据...

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/147026632-035bcaa6-a9b7-4cc4-969f-c0f8eb04d401.png)

**Comment by livelyPeng** [comment]
这TM不就是吗？还有什么JB叫半选？选就是选了 没选就是没选，半选是 头部的选中状态，

**Comment by huochangying** [comment]
狗叫什么，就你这素质还搞什么开源，垃圾
