### ISSUE TITLE
树形表格已经设置了row-key属性，但是设置expand-row-keys绑定数组，默认还是不展开。

### ISSUE THREAD

**Issue by KieleYuan** [u-leo/umy-ui#129]
你好，请问我已经设置了row-key，且expand-row-keys绑定的数组是row-key属性值组成的数组。但是在u-table中渲染的时候默认展开没有起效。可以看下是为什么吗？

**Comment by livelyPeng** [comment]
给复现链接

**Comment by KieleYuan** [comment]
![image](https://user-images.githubusercontent.com/96520155/147071627-2d93ae91-f05a-446d-9602-42400ce60561.png)
![image](https://user-images.githubusercontent.com/96520155/147071685-dd5c3f54-2751-4bb1-884b-22ed9dccbad1.png)
我在created中把expand-row-keys绑定的数组设置为之前存储的展开行的row-key数组。

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/147072186-4acc1a5e-bc59-41cc-aa91-833d2dba2ca3.png)
 眼瞎吗？

**Comment by livelyPeng** [comment]
还是说你在文档哪里看见 u-table虚拟表格看见了  展开行？、

**Comment by KieleYuan** [comment]
这个没有考虑支持下吗
