### ISSUE TITLE
滚动条样式出错

### ISSUE THREAD

**Issue by MonreeStudio** [u-leo/umy-ui#13]
![download](https://user-images.githubusercontent.com/32088844/99505284-988e0700-29bb-11eb-8d0c-c548eb968ae5.png)

**Comment by livelyPeng** [comment]
干嘛搞个110%？如果需要动态宽高度  你需要刷新表格！

**Comment by MonreeStudio** [comment]
？？？？什么叫搞个100%？？
就是用户平时缩放页面的操作，UI出现这种情况。。。。。
