### ISSUE TITLE
u-table 偶尔 会出现表格渲染不出，滚动条滚动一下就马上刷新出来了有什么解决办法吗？

### ISSUE THREAD

**Issue by Wilburn-hub** [u-leo/umy-ui#130]
<img width="235" alt="iShot2021-12-20 19 20 56" src="https://user-images.githubusercontent.com/64264596/147071222-9bb82a0a-38bd-4b44-bf64-a97d1d029be1.png">
开始用v-if切换两个tab下的表格，后来看到官网用到v-show，也改成v-show来控制切换tab的表格，但是偶尔还是会表格渲染不出来，留下空白，滚动条滚动一下就好了，还望作者大大指点一下

**Comment by Wilburn-hub** [comment]
![image](https://user-images.githubusercontent.com/64264596/147071781-d0ee8fcb-8ca9-4108-8d54-42a92855fa50.png)

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/multi-label-switching 您能去看文档吗？再见！

**Comment by Wilburn-hub** [comment]
您好，我也照做了
![image](https://user-images.githubusercontent.com/64264596/147072897-6793281a-0f53-4483-aca5-6707cdfec10f.png)
可是还是会偶尔出现

**Comment by Wilburn-hub** [comment]
实在没办法解决才来麻烦您

**Comment by livelyPeng** [comment]
自己去找问题大哥，文档没问题， 切换的时候你肯定是重新 赋值了数据 异步了。，导致dolayout提前执行了，尝试延迟 下dolayout

**Comment by Wilburn-hub** [comment]
感谢
