### ISSUE TITLE
使用u-table 如何获取表格上实时渲染的是哪些数据？

### ISSUE THREAD

**Issue by 934556826** [u-leo/umy-ui#138]
ux-gird可以通过getTableData()获取当前表格的数据，那请问下u-table应该怎么做呢
将万分感谢您的回复

**Comment by livelyPeng** [comment]
tableExample | 表格实例方式，调用就会返回table实例  调用这个方法，里面去找下面2个字段，他表示，当前data数据的开始和结束的 下标，然后自己截取你的data即可啦！   
start: 0,
            end: 0,
