### ISSUE TITLE
如果展开的行高度超过表格高度，应该怎么处理？

### ISSUE THREAD

**Issue by vrcms** [u-leo/umy-ui#14]
以这个展开为例，https://www.umyui.com/umycomponent/expandRow

`<template v-slot:content="{ row, rowIndex }">
                   <template>
                       <ul>
                           <li>
                               <span>Name：</span>
                               <span>{{ row.name }}</span>
                           </li>
                           <li>
                               <span>Name：</span>
                               <span>{{ row.age }}</span>
                           </li>
                       </ul>
                   </template>
               </template>`

目前表格为500的高度，如果这段代码中的**单行展开**的显示高度超过500（多加几个换行使之超500高度），那么滚动就有问题的，该如何处理？

**Comment by livelyPeng** [comment]
It's not recommended to expand. I suggest that you use the click pop-up window to display your expanded content

**Comment by livelyPeng** [comment]
or expand the content area, set a maximum height, and use the scroll bar

**Comment by vrcms** [comment]
1.点击弹窗显示扩展内容可以，但点击并展开这个行为，本身是优化交互的。不然要展开干嘛
2.设置max-height会产生两个scroll bar ，也是不好的

3.哪里可以看到代码中何时更新list ?

**Comment by livelyPeng** [comment]
the table must have a height，如果展开内容高于表格，那这是没办法的。除非你不给表格高度。不然没得办法！不给表格高度就是自适应，自适应高度不可以虚拟滚动！二选其一！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason.lu"<notifications@github.com&gt;; 
发送时间: 2020年11月23日(星期一) 下午4:55
收件人: "u-leo/umy-ui"<umy-ui@noreply.github.com&gt;; 
抄送: "travel96"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [u-leo/umy-ui] 如果展开的行高度超过表格高度，应该怎么处理？ (#14)





 
1.点击弹窗显示扩展内容可以，但点击并展开这个行为，本身是优化交互的。不然要展开干嘛
 2.设置max-height会产生两个scroll bar ，也是不好的
 
3.哪里可以看到代码中何时更新list ?
