### ISSUE TITLE
electron 中代替elementui table 数据不渲染

### ISSUE THREAD

**Issue by zzh466** [u-leo/umy-ui#143]
electron版本 15.2.0； vue版本 2.5.16； umy ui版本1.1.6；element版本 2.15.6；element table能正常渲染。u-table只有边框，没有对应的表头和内容，无报错信息

**Comment by livelyPeng** [comment]
electron 好像需要单独按安装umy-table   就是需要单独 引入umy-table，  import umyTable from "umy-table"
vue.use(umyTable )
