### ISSUE TITLE
ux-grid可以在不用多级表头的情况下取消横向虚拟吗？

### ISSUE THREAD

**Issue by HuangZhongdi** [u-leo/umy-ui#144]
u-table的合并会错位，ux-grid的merge-cells合并列在取消横向虚拟时不会错位，所以想问问能不能在不用多级表头的情况下取消横向虚拟？

**Comment by crow04** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HuangZhongdi** [comment]
> u-table的合并会错位，ux-grid的merge-cells合并列在取消横向虚拟时不会错位，所以想问问能不能在不用多级表头的情况下取消横向虚拟？

**Comment by HuangZhongdi** [comment]
搞错了，ux-grid数据多了合并也会错位，楼主不用回我了
