### ISSUE TITLE
左右固定列，上下滚动不同步

### ISSUE THREAD

**Issue by xdwxls** [u-leo/umy-ui#15]
左右固定列，上下滚动不同步,请问如何解决呢

**Comment by livelyPeng** [comment]
这个跟电脑 有很大关系哈，以为你可能固定列了，然后呢  代表多渲染个表格，节点就多了，。你可换个配置好的电脑看看，或者你用下ux?

**Comment by zliuxia** [comment]
ux的树形表格不支持虚拟滚动？
