### ISSUE TITLE
合并列头在遇到大数据时会出现渲染的问题

### ISSUE THREAD

**Issue by wjsq0705** [u-leo/umy-ui#152]
![image](https://user-images.githubusercontent.com/30041736/168504818-feed69b0-4ccc-412d-bba9-7ebc0ed86004.png)

看了下dom结构，没渲染成功可能是因为表格优化时只显示了当前视野内的数据，被滚动到上面的数据并没有被渲染就会出现问题。

**Comment by wjsq0705** [comment]
补充：鼠标往上滚动还会渲染出来，这个问题也只出现在顶部。

**Comment by livelyPeng** [comment]
多级头不支持 合并单元格

**Comment by wjsq0705** [comment]
> 多级头不支持合并单元格

这和多级表头没关系吧，这不是因为固定列头的问题吗，我取消了多级表头问题依旧存在。

**Comment by livelyPeng** [comment]
固定列部分，不可以合并单元格！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月16日(星期一) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 合并列头在遇到大数据时会出现渲染的问题 (Issue #152)





  
多级头不支持合并单元格
  
这和多级表头没关系吧，这不是因为固定列头的问题吗，我取消了多级表头问题依旧存在。
