### ISSUE TITLE
ux-grid列固定，如果数据行有expand功能，展开时，布局会变混乱。

### ISSUE THREAD

**Issue by clude** [u-leo/umy-ui#154]
你好，如标题描述，当ux-grid首列固定时，展开某行时会造成行布局混乱。
<img width="788" alt="image" src="https://user-images.githubusercontent.com/3115168/168843104-a718206f-e542-4617-9869-b393e14a9d2e.png">

想修改下代码修复该issue, 发现umy-table源码并不完整，能否修复该bug, 或者提供下umy-table源码？

**Comment by livelyPeng** [comment]
固定列不可以有展开，你改也没用。不是那么好办！
