### ISSUE TITLE
ux-grid使用merge-cells后列的fixed属性失效

### ISSUE THREAD

**Issue by 5Iris5** [u-leo/umy-ui#155]
您好，如标题所示，ux-grid使用merge-cells后固定列失效，效果如下所示：
![xx](https://user-images.githubusercontent.com/30197396/170659024-ff274d5c-2337-468f-b2c7-0574c1dbf18b.gif)
代码片段如下：
![image](https://user-images.githubusercontent.com/30197396/170659173-ae0d7e2f-fb6a-4d61-8583-f933349e5948.png)
通常采用ux-grid的场景列字段会很多，在这个前提下固定列是非常必要的，麻烦作者提供下此问题的解决方案，谢谢！

**Comment by livelyPeng** [comment]
目前不支持
