### ISSUE TITLE
ux-grid树表格中使用ux-grid展开行，setAllTreeExpand方法可以展开树型全部节点，但是setAllRowExpand方法调用时不能展开行

### ISSUE THREAD

**Issue by luoxiaolongdidi** [u-leo/umy-ui#158]
` <ux-grid
          ref="plTable"
          border
          :height="tableHeight"
          :show-overflow="true"
          :show-header-overflow="true"
          size="mini"
          style="margin-top: 10px"
          :cell-class-name="setClass"
          :expand-config="{expandAll: false}"
          :tree-config="{children: 'listChildren',
                         expandAll: false}"
        >
          <ux-table-column title="分级编号" field="levelCode" width="90" tree-node />

          <ux-table-column type="expand" width="20">
            <template v-slot:content="{ row }">
              <template>
                <div v-show="row.level==3" class="built-in-table">
                  <div style=" width: 90vw;">
                    <resource-box v-if="row.resource&&row.resource.length>0" :list="row.resource" />
                    <div v-else class="no-data">暂无数据！</div>
                  </div>
                </div>
              </template>
            </template>

          </ux-table-column>
          <ux-table-column
            v-for="(item, c) in tableField"
            :key="c"
            :field="item.prop"
            :title="item.label"
            :align="item.align"
            :min-width="item.width"
          />

        </ux-grid>`

` this.$refs.plTable.setAllTreeExpand(true)
        this.$nextTick(() => {
          this.$refs.plTable.setAllRowExpand(true)
        })`

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/expandRow

**Comment by luoxiaolongdidi** [comment]
`<ux-grid
          ref="plTable"
          border
          :height="tableHeight"
          :show-overflow="true"
          :show-header-overflow="true"
          size="mini"
          style="margin-top: 10px"
          :cell-class-name="setClass"
          :expand-config="{expandAll: false}"
          :tree-config="{children: 'listChildren',
                         expandAll: false}"
        >
          <ux-table-column title="分级编号" field="levelCode" width="90" tree-node />
          <ux-table-column type="expand" width="20">
            <template v-slot:content="{ row }">
              <template>
                <div v-show="row.level==3" class="built-in-table">
                  <div style=" width: 90vw;">
                    <resource-box v-if="row.resource&&row.resource.length>0" :list="row.resource" />
                    <div v-else class="no-data">暂无数据！</div>
                  </div>
                </div>
              </template>
            </template>
          </ux-table-column>
          <ux-table-column
            v-for="(item, c) in tableField"
            :key="c"
            :field="item.prop"
            :title="item.label"
            :align="item.align"
            :min-width="item.width"
          />
        </ux-grid>`
在多级树型结构下的展开所有行方法是失效的，API没有用

**Comment by luoxiaolongdidi** [comment]
@livelyPeng

**Comment by livelyPeng** [comment]
写demo

**Comment by luoxiaolongdidi** [comment]
@livelyPeng http://www.ga1993.net/test/#/test

**Comment by livelyPeng** [comment]
没问题啊， 再说一次 不可以展开所有行！不可以每个节点一个展开行！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 上午10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux-grid树表格中使用ux-grid展开行，setAllTreeExpand方法可以展开树型全部节点，但是setAllRowExpand方法调用时不能展开行 (Issue #158)





 
@livelyPeng http://www.ga1993.net/test/#/test
