### ISSUE TITLE
table高度不能随父元素的高度自适应

### ISSUE THREAD

**Issue by mmclofe** [u-leo/umy-ui#159]
您好，我想请教下table高度不能随父元素的高度自适应的问题![image](https://user-images.githubusercontent.com/44460247/172829748-d383bfb9-14b0-4801-b281-535e12095373.png)
我给table设置了max-height，在table显示出来的高度是计算出来固定的，而没有随父元素高度自适应
麻烦帮我看下呢

**Comment by mmclofe** [comment]
我是从pl-table组件转战到umy-ui的，换table组件就遇到这个问题，我们页面布局，table是flex:1，自由分配剩余空间的，但是现在
ux-grid好像是由我传进去的table高度固定了，不会受外界影响，原来的pl-table是没有这个问题的，麻烦大佬帮我看下是我使用组件的方式不对吗

**Comment by mmclofe** [comment]
最后通过在页面计算table所需高度再传入给table实现了

**Comment by livelyPeng** [comment]
最后通过在页面计算table所需高度再传入给table实现了  这就是答案
