### ISSUE TITLE
渲染初始数据后，insertRow插入一行新数据，然后可以做到替换掉这整行的数据吗

### ISSUE THREAD

**Issue by 690753315** [u-leo/umy-ui#160]
1. 用reloadRow(row, 新数据)可以更新替换掉  初始化时就存在tableData中的  某行数据所有字段的值。
2. 于是试着用insertRow插入一行新数据，然后reloadRow更新替换掉插入的这整行数据，并不行。

于是想着先把新插入的数据保存到tableData后，再通过tableData.splice(目标索引,1,新数据)替换整行数据，再重新reloadData，也失败了。
但是如果执行2后再执行1，再执行2，新插入的数据就可以被更新了（不理解这样为啥就可以）

**Comment by livelyPeng** [comment]
修改数据 直接修改数据源
