### ISSUE TITLE
ux-grid关闭x轴虚拟滚动后，可以实现单元格自动换行，但是开启树形连接线样式就错位了

### ISSUE THREAD

**Issue by Jack-Dh** [u-leo/umy-ui#161]
![image](https://user-images.githubusercontent.com/33785393/174707916-f9f12e90-07dd-4daf-8fcd-c5be7233673c.png)
ux-grid关闭x轴虚拟滚动后，可以实现单元格自动换行，但是开启树形连接线样式就错位了

**Comment by livelyPeng** [comment]
我看看呢

**Comment by hotFixMan** [comment]
@Jack-Dh 你说如何关闭x轴虚拟滚动的

**Comment by livelyPeng** [comment]
@hotFixMan https://github.com/u-leo/umy-ui/issues/91
