### ISSUE TITLE
checkbox 默认选中 禁止修改 导致checkbox选中状态不展示

### ISSUE THREAD

**Issue by c511920617** [u-leo/umy-ui#163]
表格 checkbox-config  checkRowKeys 配置默认选中  checkMethod 配置是否可选，会把默认选中的状态给取消。
![image](https://user-images.githubusercontent.com/26077852/175487962-30c9b1ef-c8a1-4fa9-8ba9-12f7fb341f24.png)
![image](https://user-images.githubusercontent.com/26077852/175488043-4a0b7a8a-8e71-4caf-8821-a598e8c9a5c1.png)

**Comment by livelyPeng** [comment]
checkbox选中状态不展示， 试试 调用勾选方法 主动把它勾上

**Comment by c511920617** [comment]
调用 setTreeExpand 方法主动选中，依然是勾选不上的

**Comment by livelyPeng** [comment]
写个demo 复现链接
