### ISSUE TITLE
更新表头导致固定在左右边的操作列样式错位

### ISSUE THREAD

**Issue by Gaoyuan1024** [u-leo/umy-ui#166]
![2022714164130](https://user-images.githubusercontent.com/30463377/178954090-e55a7260-3762-4dc7-9388-850bb6454d89.jpg)

![1657788043285](https://user-images.githubusercontent.com/30463377/178941948-ffa776a7-ef17-4282-9c1c-70c30b5035bd.jpg)

![6c3e65eed54f13dcfe7935fe149a820](https://user-images.githubusercontent.com/30463377/178954124-2d348a7e-b0cc-44f4-afe1-f16fcbd2207f.png)

![1ef3e11982de86dac00beea77fd9d5c](https://user-images.githubusercontent.com/30463377/178954146-c7fdd39e-ba4c-4806-8a1a-57b928a7b4ab.png)

**Comment by Gaoyuan1024** [comment]
.// 更新表格视图
this.$nextTick(()=>{
    this.$refs.table.doLayout();
})

**Comment by livelyPeng** [comment]
Thank you for your feedback. This problem has been solved. Close it
