### ISSUE TITLE
一个新的期望功能

### ISSUE THREAD

**Issue by zqa2048** [u-leo/umy-ui#17]
感谢大佬们的组件库，这个table感觉功能很完整了，请问后续会增加查询表格吗~

**Comment by livelyPeng** [comment]
@zqa2048 查询可以自己去写哇！你写  我写 都是去遍历！

**Comment by zqa2048** [comment]
> @zqa2048 查询可以自己去写哇！你写 我写 都是去遍历！
好的好的，我自己写也可以，谢谢回答啦
