### ISSUE TITLE
开发文档这个网站巨卡无比！！！

### ISSUE THREAD

**Issue by MinionsZQG** [u-leo/umy-ui#174]
开发文档这个网站巨卡无比！！！

**Comment by misswell** [comment]
官网太卡了！！

**Comment by livelyPeng** [comment]
不能说卡把，那是带宽小了，没钱买。 然后umy官网加载的js文件大了，导致加载速度慢。f12打开 看看加载脚本的速度就知道了

**Comment by livelyPeng** [comment]
多等会儿，加载出来了，不清楚缓存 下次访问就很快的
