### ISSUE TITLE
自适应高度与浮动列的冲突

### ISSUE THREAD

**Issue by YUEJINYUAN** [u-leo/umy-ui#179]
正常使用的时候，如果列的内容撑开（比如多选或者多行文本），会导致当前列的高度扩增大于设定的rowheight值，而如果有fixed标注的浮动列，则因为浮动列高度仍是设定高度而错位，如下图
![1662019406325](https://user-images.githubusercontent.com/37728521/187864384-d7dec9f5-48ba-4b0c-b25f-ebae7f1f6a1e.jpg)

element里面的方案是=》一次性渲染出三张表（左fixed 主 右fixed） 并在fixed表隐藏主表内容 来保证高度的统一

**Comment by livelyPeng** [comment]
https://github.com/u-leo/umy-ui/issues/32
