### ISSUE TITLE
UTable中的 show-body-overflow 设置 ‘tooltip’ 能不能支持鼠标移入

### ISSUE THREAD

**Issue by ah-smile** [u-leo/umy-ui#182]
问题：UTable中的 show-body-overflow 设置 ‘tooltip’ 能不能支持鼠标移入
使用场景：移入复制 tooltip 中的内容

**Comment by livelyPeng** [comment]
不能，自己在单元格里面放个复制按钮，点击复制。 大家都是这样干的。element也不可以移入

**Comment by yrx0823** [comment]
> 不能，自己在单元格里面放个复制按钮，点击复制。 大家都是这样干的。element也不可以移入

element tooltip可以鼠标移入啊，可以不可以支持一下~
