### ISSUE TITLE
[咨询]umy-ui ui-grid不是用element-ui的表单组件下能支持输入吗？

### ISSUE THREAD

**Issue by ArmyMedalMei** [u-leo/umy-ui#183]
[咨询]umy-ui ui-grid不是用element-ui的表单组件下能支持输入吗？
![image](https://user-images.githubusercontent.com/19337530/190411387-8e65775a-ed38-4931-8853-6c70f4f4330f.png)

**Comment by livelyPeng** [comment]
可以，只是无法实现：
![image](https://user-images.githubusercontent.com/32978177/190536435-23976dcb-622c-4d60-85f8-72bfc38dfb1d.png)
这个东西了

**Comment by ArmyMedalMei** [comment]
嗯，不需要autofocus，就只是填写一个字符串就行，应该怎么做呢？

**Comment by ArmyMedalMei** [comment]
我怎么设置都不对，请教大佬应该怎么设置ux-table-column属性呢？
