### ISSUE TITLE
与 elementUI2.15.6 以上版本的兼容性问题

### ISSUE THREAD

**Issue by silenceofWT** [u-leo/umy-ui#184]
在项目中使用了 elementUI2.15.6 及其以后版本
问题一：
u-table
 tree-config 配置如下：
{
    children: 'documents',
    iconClose: 'el-icon-arrow-right',
    iconOpen: 'el-icon-arrow-down',
   expandAll: false
}
箭头在表格中显示错乱
问题二：
非固定列中包含固定列，会导致重复

**Comment by livelyPeng** [comment]
那就建议你使用ux-
