### ISSUE TITLE
官网加载慢

### ISSUE THREAD

**Issue by winteroo** [u-leo/umy-ui#19]
建议去掉官网的音乐播放器，严重拖慢了网页的加载速度，望作者采纳，每次进官网都加载很久真的很难受啊

**Comment by livelyPeng** [comment]
好的，建议不错，就是因为那个音乐文件太大，加上我们带宽小了。  但是我比较喜欢听歌。所以你最好加载一次网站，不要清除缓存，下次进来就不卡了啊！

**Comment by cyb2cyb** [comment]
> 好的，建议不错，就是因为那个音乐文件太大，加上我们带宽小了。 但是我比较喜欢听歌。所以你最好加载一次网站，不要清除缓存，下次进来就不卡了啊！

咦？ 还有歌？ 还有，组件好用，谢大佬解我燃眉之急
