### ISSUE TITLE
将Element版本升级到2.15.13, el-table表格全选报错

### ISSUE THREAD

**Issue by whatlin** [u-leo/umy-ui#204]
![image](https://user-images.githubusercontent.com/67350580/226237019-0c5be4b8-30ce-453a-b4b9-047e446b568e.png)

**Comment by whatlin** [comment]
大佬这直接关闭 是没问题吗？

**Comment by whatlin** [comment]
@livelyPeng 关闭了是没问题吗？大佬

**Comment by livelyPeng** [comment]
嗯，不认为 这个跟umy有关系。 如果你又问题，建议写出复现链接
