### ISSUE TITLE
屏蔽勾选列后，自定义表头里的视图无法及时更新

### ISSUE THREAD

**Issue by July-20** [u-leo/umy-ui#206]
1. 用以下代码，点击姓名表头，姓名表头会变成fale/true
2. 手动屏蔽勾选列，再点击姓名表头，姓名表头视图无更新，对应的数据nameFlag会随着点击不断更新
3. 取消屏蔽勾选列，又恢复正常

`

        <u-table :data="[]" use-virtual max-height="550px" :row-height="55" :data-changes-scroll-top="false">
            <u-table-column type="selection" width="50" align="center" key="selection" />
            <u-table-column type="index" label="序号" width="50" align="center" key="index" />
            <u-table-column prop="nickName" label="姓名" align="center" key="nickName" width="120">
                    <template slot="header">
                        <span @click="nameFlag = !nameFlag">{{ nameFlag }}</span>
                    </template>
                </u-table-column>
        </u-table>
`

https://user-images.githubusercontent.com/56582712/227762036-ac875321-2cda-4da8-9b29-a6a0fc4ccd0b.mp4

**Comment by livelyPeng** [comment]
需要刷新表格，方法看文档
