### ISSUE TITLE
您好，能否有方法或通过代码直接进入键盘导航的单元格选中状态而不是点击单元格的时候才会选中？ 我想让它的导航定位在某个单元格上，但是又不进入该单元格的编辑状态。

### ISSUE THREAD

**Issue by a875030453** [u-leo/umy-ui#209]
![image](https://user-images.githubusercontent.com/49543657/230699458-54cfb7a8-9f4a-4325-9546-d02aa7f13547.png)

**Comment by livelyPeng** [comment]
没有
