### ISSUE TITLE
这作者心态不行，问下就喷人，建议不要用，有问题也不会给你解决，fork自己借鉴吧用还是算了

### ISSUE THREAD

**Issue by WinKi7** [u-leo/umy-ui#21]

**Comment by livelyPeng** [comment]
@WinKi7 有好远滚好远，记住了吗，你就说找茬的哈狗，你自己去需求自己去实现，人家表格服务多数人需求，你自己不是这个需求，请你自己去实现，不要问弱智问题！

**Comment by livelyPeng** [comment]
![Uploading image.png…]()

**Comment by livelyPeng** [comment]
注：当你选中了单元格，然后你按下任意键就可以获取焦点进行编辑,除了功能键，默认直接清空内容

注：当输入框是编辑状态，可以通过tab按键来切换单元格，不可以使用上下左右按钮来切换单元格，因为此时是编辑状态

注：当不是编辑状态，你可以通过上下左右按钮来切换单元格

注：当输入框是编辑状态，你可以使用失去焦点或者按下esc按键退出编辑状态


人家说得很清楚，编辑状态，你不可以上下左右切换，你还找茬。bb奈奈    你自己不会。咋的 人家就应该免费 给你说？哦 ，还不准人家说你菜？哦？
