### ISSUE TITLE
 表格中 type=selection 列中的选择框如何调整为不可编辑

### ISSUE THREAD

**Issue by 244209156** [u-leo/umy-ui#211]
<u-table-column
        type="selection"
        width="55"
        align="center"
        :disabled="true"
      />   
加  disabled 属性没用，  有没有办法可以不让它可编辑，求大佬指教

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/235047922-a3b30d0b-a807-482a-ad47-cc31ac036f20.png)
