### ISSUE TITLE
合并往下滑样式错乱

### ISSUE THREAD

**Issue by Yhui11** [u-leo/umy-ui#214]
因为数据比较多，然后还有合并功能，然后使用了ux-grid,加载速度快了，但是往下滑会出现样式错乱，并且还有多列空白
![企业微信截图_16824091732142](https://user-images.githubusercontent.com/69672771/234211899-a0bbdeb2-4799-4f84-ace4-6cdc49500096.png)
![企业微信截图_16824091732142](https://user-images.githubusercontent.com/69672771/234212048-b590d31c-cc1c-42ce-8163-1cd280de4e6c.png)

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/mergeCells
