### ISSUE TITLE
filters筛选过滤数据异步无法获取过滤列表

### ISSUE THREAD

**Issue by leemanvin** [u-leo/umy-ui#215]
我的表格数据是通过异步请求获取的，第一列的筛选列表里的筛选选项也是异步请求获取的，表格的数据可以获取的到，但是filter里的列表数据怎么都获取不到，想问下filter是不是不支持异步？但是原生的el-table是可以获取的到，这是我的部分代码:
![image](https://user-images.githubusercontent.com/82501944/234323954-3dc2375a-dd6b-476b-9560-3f9a7fe6c7b7.png)
![image](https://user-images.githubusercontent.com/82501944/234324248-5f7182d4-8d33-4a19-8012-e9d3f04c91cf.png)
![image](https://user-images.githubusercontent.com/82501944/234324524-8d6d3a3c-d721-4a5e-b909-72ba17e27d95.png)
![image](https://user-images.githubusercontent.com/82501944/234323030-e46eb7de-3579-46e6-a1e8-80a2ea2a911b.png)

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/ux-grid-screen
