### ISSUE TITLE
关于编辑表格的问题

### ISSUE THREAD

**Issue by ZerroRt** [u-leo/umy-ui#216]
编辑表格是和ux-grid绑定在一起的吗？现在我只想用编辑功能不想用虚拟滚动，有没有什么办法设置呢？
之所以问这个问题，是因为我在开发中遇到了一个很奇怪的现象，设置ux-grid高度之后，有时在非编辑状态滚动列表，即将滚动到最底下的时候，滚动就会反复回滚，无法滚动到最底下。

**Comment by livelyPeng** [comment]
设置ux-grid高度之后，有时在非编辑状态滚动列表，即将滚动到最底下的时候，滚动就会反复回滚，无法滚动到最底下。 这个问题是自己问题，表格示例中没有出现  无法滚动最底部
1. 现在我只想用编辑功能不想用虚拟滚动，有没有什么办法设置呢？ https://github.com/u-leo/umy-ui/issues/91 关闭滚动
