### ISSUE TITLE
请问过滤后的表格数据该如何获取?

### ISSUE THREAD

**Issue by leemanvin** [u-leo/umy-ui#217]
想问下作者过滤后的表格数据该如何获取，原生el-table可以通过this.$refs.filterTable.store.states.filteredData获取到过滤后的表格数据，我试过在this.$refs.filterTable下找filter相关的字段，但没看到有，只有个filterchange()的方法，这个方法该如何使用，需要传什么参数吗？

**Comment by leemanvin** [comment]
已经自己解决了，没办法直接获取，给表格增加了个checkbox，过滤之后全选，然后通过获取选中的行获取到了...

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/235047397-036775b7-d508-4775-93ac-c2a6f22efbf5.png)
