### ISSUE TITLE
merge-cells动态修改不生效问题

### ISSUE THREAD

**Issue by Evinzj** [u-leo/umy-ui#220]
ux-grid使用合并单元格:merge-cells="mergeCells"，动态去改mergeCells变量，不生效是为什么？ 
只有放data里面初始化的时候是生效的。后面通过方法去修改都不生效。
修改完后调用this.$refs.plxTable.doLayout(); 也不行

**Comment by lx11573** [comment]
在实例中有个 setMergeCells 方法
可以通过这个方法手动更新

**Comment by Evinzj** [comment]
> 在实例中有个 setMergeCells 方法 可以通过这个方法手动更新

你好，没有效果。是通过tableExample()拿到实例再去setMergeCells()吗？没有报错，但也没有set成功
this.$refs.detailTable.tableExample().setMergeCells(
        [
          { row: 0, col: 0, rowspan: 5, colspan: 1 },
        ]
      );

**Comment by Evinzj** [comment]
> > > 在实例中有个 setMergeCells 方法 可以通过这个方法手动更新
> > 
> > 
> > 你好，没有效果。是通过tableExample()拿到实例再去setMergeCells()吗？没有报错，但也没有set成功 this.$refs.detailTable.tableExample().setMergeCells( [ { row: 0, col: 0, rowspan: 5, colspan: 1 }, ] );
> 
> 是可以的，不知道你到底如何操作的，不过我用官网的示例代码是可以手动更新合并的

谢谢，可以了。动态变更变量mergeCells是可以实现的

**Comment by AshleyCry** [comment]
我也遇到了相同的问题，请问您最后是怎么解决的呢

**Comment by AshleyCry** [comment]
> 我也遇到了相同的问题，请问您最后是怎么解决的呢

我试了将mergeCell写死在data中，但也是不生效的

**Comment by ArleneShine** [comment]
@lx11573 @Evinzj 你好，动态改变mergeCells没有生效，请问要怎么写才可以？能给下示例更好，感谢~

**Comment by ArleneShine** [comment]
补充说明，用this.$refs.table.reloadData(data)可以使mergeCells生效，但会清空表格的状态，比如排序状态会被清空。请问有其他方法可以解决这个问题吗？希望表格状态不被影响

**Comment by ArleneShine** [comment]
我先用这个方法解决问题了：
```lang=js
// 重置数据
this.$refs.table.reloadData(tableData)
// 恢复排序状态
this.$refs.table.sort(field, order)
```
如果大家有更好的方法，麻烦@我，让我学习下，感谢啦~
