### ISSUE TITLE
表格检验如何阻止弹出默认的提示框

### ISSUE THREAD

**Issue by ShenLiBZ** [u-leo/umy-ui#226]
表格检验如何阻止弹出默认的提示框

**Comment by livelyPeng** [comment]
？

**Comment by ShenLiBZ** [comment]
![image](https://github.com/u-leo/umy-ui/assets/41415846/5e267423-7aa0-418c-9514-dbe6277442d9)

**Comment by ShenLiBZ** [comment]
![image](https://github.com/u-leo/umy-ui/assets/41415846/687aa370-45ec-4371-a67a-8d46501f7071)
只保留右边的弹框，阻止弹出中间的警告框

**Comment by livelyPeng** [comment]
![image](https://github.com/u-leo/umy-ui/assets/32978177/495402e6-d174-46fd-8c9c-61a070313d3f)
