### ISSUE TITLE
表格编辑 插入或新增一行 不重新查询 可以重置他们的插入和更新的状态吗

### ISSUE THREAD

**Issue by zhingyy** [u-leo/umy-ui#229]

**Comment by zhingyy** [comment]
const insertRecords = this.$refs["uxGrid"].getInsertRecords();
      const updateRecords = this.$refs["uxGrid"].getUpdateRecords();
作者大大，我获取新增行，和更新行，不重新查询更新表格数据，可以重置他们的状态，以便下次获取数据新增行，和更新行，是新的一轮

**Comment by livelyPeng** [comment]
？
