### ISSUE TITLE
请问u-table 使用sortable排序后怎么获取排序后的数据？

### ISSUE THREAD

**Issue by tianyawhl123** [u-leo/umy-ui#236]
请问sortable排序后怎么获取排序后的数据？

**Comment by livelyPeng** [comment]
直接获取 表格实例方法，然后里面又表格数据

**Comment by 4ever88** [comment]
> 直接获取 表格实例方法，然后里面又表格数据

我也有相同的问题。请问是哪个方法？请告知谢谢你。

**Comment by crow04** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
