### ISSUE TITLE
横向滚动后到尾部，手动编辑行方法setActiveRow失效

### ISSUE THREAD

**Issue by WANGXIAOYU1995** [u-leo/umy-ui#237]
页面点击编辑行，setActiveRow方法正常调用执行了，ref也拿到了，但是页面无效果，将滚动条拖至左边一点效果就正常了，作者大大帮忙看看

**Comment by WANGXIAOYU1995** [comment]
已解决...    解决方案  手动将滚动条重置到左边  再把setActiveRow方法放在宏任务执行。虽然不知道为啥会出这个bug也算效果实现了
this.curTableRef.pagingScrollTopLeft({ left: 0 })
      setTimeout(() => {
        this.curTableRef.setActiveRow(row)
  }, 0)

**Comment by wangqyuan** [comment]
pagingScrollTopLeft能不能不重置到左边， 用户有、体验不好， 保持滚动条原来的位置， 可是先left0然后left到原来位置不生效啊， 这个pagingScrollTopLeft怎么用啊， 随便写一个固定数值也不生效

**Comment by WANGXIAOYU1995** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangqyuan** [comment]
能for循环想要的行row， 把所有想要的行row都用这个setActiveRow设置成激活状态吗？

**Comment by wangqyuan** [comment]
> 能for循环想要的行row， 把所有想要的行row都用这个setActiveRow设置成激活状态吗？

setActiveRow不能通过遍历设置多行为可编辑状态， 如果要设置很多行为可编辑状态只能参考组件示例中的方式：编辑表格->输入框全部显示（采取cell编辑方式，本质上通过样式构造假输入框， 假编辑效果）

**Comment by wangqyuan** [comment]
> pagingScrollTopLeft能不能不重置到左边， 用户有、体验不好， 保持滚动条原来的位置， 可是先left0然后left到原来位置不生效啊， 这个pagingScrollTopLeft怎么用啊， 随便写一个固定数值也不生效


pagingScrollTopLeft的参数是传两个值pagingScrollTopLeft（200， 300），200是left， 300是top，并不是对象哦，

**Comment by wangqyuan** [comment]
> 页面点击编辑行，setActiveRow方法正常调用执行了，ref也拿到了，但是页面无效果，将滚动条拖至左边一点效果就正常了，作者大大帮忙看看

但是设置pagingScrollTopLeft回滚到用户之前滚动到的地方， 只要left不为0， 那编辑就会失效， 哎！用户体验不好！！！咋办哦
