### ISSUE TITLE
涉及到固定列的表头，进行拖拽时，宽度异常

### ISSUE THREAD

**Issue by wangchuanwc** [u-leo/umy-ui#240]
设置一个固定列，且设置宽度，当整体表格未出现横向滚动条时，拖拽固定列的宽度，会出现宽度错位异常的情况，固定列的右侧会多出一列空白列，查看调试控制台，发现，固定列的宽度是拖拽的宽度，但是所有列为了满足铺满全屏，宽度和固定列的宽度不一致，导致异常
![image](https://github.com/u-leo/umy-ui/assets/13955674/c7a6a4ce-0be7-452d-8d29-5fcb4993c480)
![image](https://github.com/u-leo/umy-ui/assets/13955674/98eef9bf-a4a2-41e9-8c6c-9a532928d92a)
![Snipaste_2023-09-30_15-09-34](https://github.com/u-leo/umy-ui/assets/13955674/efe58269-0313-4f05-ad1e-c3b8d6d3983a)

**Comment by wangchuanwc** [comment]
如果该列不设置固定列，就不会出现这个问题

**Comment by livelyPeng** [comment]
加群写复习链接
