### ISSUE TITLE
表格校验 目前input添加了校验规则，默认会调用message弹窗，能否可以用户自定义是否弹窗显示

### ISSUE THREAD

**Issue by nyanboard** [u-leo/umy-ui#25]
目前投机取巧的方式是将trigger置为空，是否考虑加个属性

**Comment by livelyPeng** [comment]
你可以在这里做文章：
 const nameRules = ({ cellValue, rule }) => {
                if (!cellValue) {
                  //1. 自定义弹出，自己的框
                  2. 返回一个空字符串，
                    return new Error('名字必填')
                  3.第三步，看下面的图，当就是去隐藏本身得校验弹窗
                 } else if (cellValue.length < 2) {
                    return new Error('名字必须大于2个字符')
                }
            }
![Uploading image.png…]()

**Comment by livelyPeng** [comment]
第三步的弹窗的节点是：
<div class="elx-cell--valid"><i class="el-message__icon el-icon-error"></i><span>名字必填</span></div>

类似这样的东西。，你写个样式吧elx-cell--vali这个div隐藏掉  即可啦！

**Comment by livelyPeng** [comment]
第三步的弹窗的节点是：
<div class="elx-cell--valid"><i class="el-message__icon el-icon-error"></i><span>名字必填</span></div>

名字必填
类似这样的东西。，你写个样式吧elx-cell--vali这个div隐藏掉 即可啦！

**Comment by livelyPeng** [comment]
第三步的弹窗的节点是：‘<div class="elx-cell--valid"><i class="el-message__icon el-icon-error"></i><span>名字必填</span></div>’
类似这样的东西。，你写个样式吧elx-cell--vali这个div隐藏掉 即可啦！

**Comment by livelyPeng** [comment]
“”<div class="elx-cell--valid"><i class="el-message__icon el-icon-error"></i><span>名字必填</span></div>“”
