### ISSUE TITLE
大数据树形表格，border和stripe设置后，没有显示纵向边框

### ISSUE THREAD

**Issue by cyb2cyb** [u-leo/umy-ui#26]

**Comment by cyb2cyb** [comment]
`                    <u-table
                        ref="plTreeTable"
                        border
                        stripe
                        fixed-columns-roll
                        beautify-table
                        header-drag-style
                        :height='uTableHeight'
                        :treeConfig="{
                            children: 'children',
                            iconClose: 'el-icon-folder-add',
                            iconOpen: 'el-icon-folder-remove',
                            expandAll: false}"
                        use-virtual
                        row-id="id">`
这是配置项

**Comment by livelyPeng** [comment]
吧beautify-table去掉，你还是去看看beautify-table是啥吧，beautify-table美化样式，我写了样式给你边框干掉了。因为我们公司觉得好看。不需要边框线、！

**Comment by cyb2cyb** [comment]
> 吧beautify-table去掉，你还是去看看beautify-table是啥吧，beautify-table美化样式，我写了样式给你边框干掉了。因为我们公司觉得好看。不需要边框线、！

噢，是我没认真阅读文档。已解决。谢大佬

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/beautifyTable
