### ISSUE TITLE
右侧固定列变成透明的，不显示这一列内的文字，请问是什么原因？

### ISSUE THREAD

**Issue by crazyzzyzzy** [u-leo/umy-ui#29]

**Comment by livelyPeng** [comment]
没引入样式

**Comment by crazyzzyzzy** [comment]
好的，谢谢解答

**Comment by crazyzzyzzy** [comment]
> 没引入样式

直接引入样式会把element-ui的样式覆盖掉。我想只修改固定列出问题的这一部分，请问要怎么写样式呀，还请大佬指教。

**Comment by livelyPeng** [comment]
先引入umyui样式， 在引入 ele即可，
main.js文件：
1. 
import引入umyui样式
2

import // 引入element-ui样式

顺序不可换！ 动动脑子吧！哎
