### ISSUE TITLE
ux-table-column动态渲染不能更新

### ISSUE THREAD

**Issue by cweijan** [u-leo/umy-ui#3]
![image](https://user-images.githubusercontent.com/27798227/90382159-f5bea780-e0b0-11ea-8ed6-2d5c65815df8.png)
首先感谢老哥, 你这个性能非常牛逼, 我现在ux-table-column是动态渲染出来的, 当我重新赋值fields后, field变量没有更新, 仍旧是之前的值

**Comment by cweijan** [comment]
我改用scope.column替换field解决了, 不过这里算是bug, 因为element这里的循环变量是会更新的.

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/90460744-221d0700-e137-11ea-8f0a-9e089b260b92.png)

**Comment by livelyPeng** [comment]
根据VUE官方文档  不要这样v-for -if出现在同一个标签组件里面

**Comment by livelyPeng** [comment]
更新列 有更新列的方式

**Comment by livelyPeng** [comment]
loadColumn | 加载列配置（对于表格列需要重载、局部递增场景下可能会用到）
-- | --

**Comment by livelyPeng** [comment]
https://doc.vue-js.com/v2/guide/list.html#v-for-与-v-if-一同使用

**Comment by cweijan** [comment]
嗯嗯, 了解

**Comment by livelyPeng** [comment]
麻烦不要删除问题   后面别人会遇到 谢写
