### ISSUE TITLE
npm ls 以后报错

### ISSUE THREAD

**Issue by xhjzrq** [u-leo/umy-ui#30]
npm ERR! peer dep missing: xe-utils@>= 3, required by umy-ui@1.1.6
npm ERR! peer dep missing: xe-utils@>= 3, required by umy-table@1.1.8
每太懂 这个错误是什么

**Comment by livelyPeng** [comment]
@xhjzrq 删除nodemodule文件，删除packagelock文件  重新 npm i  这不是啥问题，请等待安装完全 使用即可，你的问题 ，我给你关闭了！
