### ISSUE TITLE
ux-grid，现在30列*50行，滚动时感觉卡顿(有左侧固定列，大部分td都是自定义内容)

### ISSUE THREAD

**Issue by joojay-liu** [u-leo/umy-ui#34]
是因为过多的自定义内容导致的么？

**Comment by livelyPeng** [comment]
自定义单元格 内容，建议看编辑型表格！

**Comment by joojay-liu** [comment]
> 自定义单元格 内容，建议看编辑型表格！

您好，我的意思的，我的ux-grid-column里放的内容，基本每一列都是<template v-slot="scope"></template>的，里面有好多逻辑判断。
卡顿是因为这个么？
