### ISSUE TITLE
使用虚拟 u-table 树组件，树形数据 data 添加或删除一行，导致树列表折叠的问题

### ISSUE THREAD

**Issue by bighone** [u-leo/umy-ui#39]
作者您好，非常感谢您提供的组件，它解决了我特别大的难题，抱拳！

有个问题想请教下，现在有一个虚拟树，展开一些节点后，可以往节点下面添加子节点，或者删除节点，但是每次添加或者删除后，树列表都会自动折叠到最顶层，而不会保持原有展开的样子，而这个时候，左侧的折叠按钮是展开状态的！

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/virtualTreeTableAddNode
https://github.com/u-leo/umy-ui/blob/master/examples/pages/umycomponent/virtualTreeTableAddNode.vue  
去看100遍吧  别问这样的问题    谢谢您呢！

**Comment by bighone** [comment]
谢谢作者的回复，问题已经解决了！

之前我是用文档中的这种方式处理的，但是结果还是一增删数据就会折叠的状况！后面，我打印了下data数据，发现内部会设置一个 pl_table_expand 属性在每个对象中，这个属性应该是用来判断是否展开状态的！

我猜测是由于data增删行后，之前的老数据没有发生变化，如果这个时候 pl_table_expand 是 true ，那么对该行调用 setTreeExpansion 的话，应该是不产生效果的。

所以，每次data数据发生改变的时候，我先对data数组中的每条数据进行 pl_table_expand = false 重置，这样就没有问题了！
