### ISSUE TITLE
固定列表格，横向可滚动，拖拽固定列下方的滚动条无法拖动

### ISSUE THREAD

**Issue by wangdong121993** [u-leo/umy-ui#4]
带多选的固定列表格，横向可滚动，拖拽固定列下方的滚动条无法拖动，官网的demo就有这个问题

**Comment by livelyPeng** [comment]
你的问题 ele就有这个问题。所以是正常的。但是文档中有解决方案  

fixed-columns-roll | 表格有固定列,同时表格有横向滚动条，有时候会导致固定列部分的横向滚动条不可拖动，是否需要解决此问题 | Boolean | — | false
-- | -- | -- | -- | --
