### ISSUE TITLE
设置第一行行高大于其他行高很多后，滚动表格会留白

### ISSUE THREAD

**Issue by objectLin** [u-leo/umy-ui#42]
![image](https://user-images.githubusercontent.com/28566505/106999549-5d80c000-67c1-11eb-8a7e-c6b8dceee912.png)
![image](https://user-images.githubusercontent.com/28566505/106999616-7d17e880-67c1-11eb-9d73-fd11fa2b8894.png)

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/dataChangesTable   （注：启用纵向虚拟滚的后不支持动态行高，如果要支持动态行高，将虚拟滚动关闭即可）。不可以行高不一样

**Comment by objectLin** [comment]
好的，那我第一行变为多行吧
