### ISSUE TITLE
Unknown custom element: <elx-grid> - did you register the component correctly

### ISSUE THREAD

**Issue by airyland** [u-leo/umy-ui#44]
使用 npm 引入，使用 ux-grid 组件会有这个错误。

按照文档安装指引，也不需要额外做其他组件引入。

翻看源码看了下，umy-ui 引用了 umy-table，ux-table-column/index.js 里是下面代码。
但是还没看明白 elx-grid 是在哪里注册， elx-table 这个依赖是在哪里。

``` js
import UxTableColumn from '../../elx-table/packages/column/src/column'
UxTableColumn.install = function(Vue) {
  Vue.component(UxTableColumn.name, UxTableColumn);
};

export default UxTableColumn;
```

**Comment by neilguangzhou** [comment]
> 使用 npm 引入，使用 ux-grid 组件会有这个错误。
> 
> 按照文档安装指引，也不需要额外做其他组件引入。
> 
> 翻看源码看了下，umy-ui 引用了 umy-table，ux-table-column/index.js 里是下面代码。
> 但是还没看明白 elx-grid 是在哪里注册， elx-table 这个依赖是在哪里。
> 
> ```js
> import UxTableColumn from '../../elx-table/packages/column/src/column'
> UxTableColumn.install = function(Vue) {
>   Vue.component(UxTableColumn.name, UxTableColumn);
> };
> 
> export default UxTableColumn;
> ```

打包编译后的代码是在node_modules/umy-table/lib/umy-table.common.js中。至于源代码，作者并未公开。
