### ISSUE TITLE
将滚动条横向拖到最右侧，表格列未对齐

### ISSUE THREAD

**Issue by putao88** [u-leo/umy-ui#45]
发现如果表格产生横向滚动条后，将滚动条拖动至表格最右侧，会出现列对不齐问题，而多出来的部分正好是滚动条的宽度，检查了示例文档的渲染元素，发现示例中多了一列元素：class="gutter"的td
但是我自己的渲染出来的表格没有这一列，请问作者大大，这个问题该怎么解决呀
![image](https://user-images.githubusercontent.com/21971266/111126508-beb06600-85ad-11eb-9970-e5154302c291.png)
示例文档：
![image](https://user-images.githubusercontent.com/21971266/111129918-99bdf200-85b1-11eb-89ff-a9078f07bb70.png)

**Comment by livelyPeng** [comment]
看github问题提问部分有个 为啥列 错位

**Comment by putao88** [comment]
看过相关问题，一般都是表格设置的宽度过大，但是我检查元素发现，不是设置的宽度问题，而是头部直接少渲染了一列（与示例文档比），这一列就正好是头部用来给滚动条的宽度
少的th:
![Uploading image.png…]()

**Comment by livelyPeng** [comment]
你说的问题 我没遇到过，文档也没出现吧。你写个demo发到群里，或者搞个链接 看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 将滚动条横向拖到最右侧，表格列未对齐 (#45)





 
看过相关问题，一般都是表格设置的宽度过大，但是我检查元素发现，不是设置的宽度问题，而是头部直接少渲染了一列（与示例文档比），这一列就正好是头部用来给滚动条的宽度
 少的th:

**Comment by putao88** [comment]
我直接使用u-table是没这样的问题的，自己进行了二次封装，不太好贴代码了；之前也是这样封装，没啥问题，我对比了下，我现在使用的版本不太一样了，我还以为是新版更新后不一样了

**Comment by putao88** [comment]
将滚动条设置的窄一点，会好一些
![image](https://user-images.githubusercontent.com/21971266/111247841-b276e800-8643-11eb-8269-7a1c91088045.png)
