### ISSUE TITLE
树形全选复选框的问题

### ISSUE THREAD

**Issue by ssibre** [u-leo/umy-ui#51]
请问：开启 checkStrictly=true 或者showHeader=false 的时候header 高度没对齐，有解决办法吗？

加QQ群了里面都是扯闲（撩骚的）篇，管理员无脑。

解决了，可能是因为覆写了样式；

但群里面都是撩骚的嗨屏，拉低分数。

**Comment by livelyPeng** [comment]
解决就好了哈！群里面自由发言，可能他们不想回答你问题吧！嗯 没对齐问题 基本是样式问题，表格是不存在啥大bug的！
