### ISSUE TITLE
getUpdateRecords()永远是空数组

### ISSUE THREAD

**Issue by ikarosu** [u-leo/umy-ui#54]
需求是，在切换tab前，检查这个表格有没有改动内容，如有要提示未保存。目前我发现的就是这个方法，但不论表格数据怎么改变，都是得到空数组

**Comment by livelyPeng** [comment]
发个demo呢

**Comment by livelyPeng** [comment]
如果你修改了行数据，然后执行了reloadRow方法。那么getUpdateRecords方法 将检测不出来变动！

**Comment by ikarosu** [comment]
> 发个demo呢

https://codepen.io/clearaki/pen/ZEeYbax?editors=1011
