### ISSUE TITLE
如果model的key是动态加上的，输入一个字符后会失焦

### ISSUE THREAD

**Issue by ikarosu** [u-leo/umy-ui#56]
某些场景下key是不固定的，需要动态插入
demo：https://codepen.io/clearaki/pen/ExWaZLd?editors=1010
不知道什么原因，第一行没问题，第二行开始就有问题

**Comment by livelyPeng** [comment]
去把 vue学精通       这样写 麻烦你了:   data: [{value: 1}, {value: 1}, {value: 1}]
