### ISSUE TITLE
umy-ui  ux-grid 横向滚动条拖拽卡顿

### ISSUE THREAD

**Issue by xzg168** [u-leo/umy-ui#59]
umy-ui  ux-grid 横向滚动条拖拽卡顿，16列108行数据横向滚动条难拖动

**Comment by livelyPeng** [comment]
不会吧  附加链接，不知道怎么写demo，看提问 issues 部分的  第三个同学

**Comment by xzg168** [comment]
> 不会吧 附加链接，不知道怎么写demo，看提问 issues 部分的 第三个同学

好了，原来直接绑data变量，换成reloadData好了、、、
