### ISSUE TITLE
表格中有一列显示的是elementui的el-image，点击大图时显示出现问题

### ISSUE THREAD

**Issue by PKXZ** [u-leo/umy-ui#61]
表格中有一列显示的是elementui的el-image，点击大图时显示出现问题。
显示的区域被表格固定列遮挡了，请问这个怎么解决

**Comment by livelyPeng** [comment]
样式问题。一看就是层级问题，自己吧el-image层级加高！想想办法  改改样式

**Comment by PKXZ** [comment]
最后解决了。。。。更新elementui版本
