### ISSUE TITLE
ux-grid虚拟表格合并行列遇到的问题

### ISSUE THREAD

**Issue by evestorm** [u-leo/umy-ui#64]
首先非常感谢作者开源了此repo，一直有在使用虚拟表格功能！非常赞的项目！

目前我们项目遇到个需求，截图如下：

![image](https://user-images.githubusercontent.com/18142851/119913512-ad61dd80-bf90-11eb-9e05-642af9996dba.png)

就是在使用 ux-grid 时，需要在合并单元格的同时（第一列日期相同时合并）固定住「日期」和「整点」两列。但发现一旦横向向左滑动表格，会把固定列的数据“挤出”：

↓这是向左滑动完一列后的效果
![image](https://user-images.githubusercontent.com/18142851/119913622-f6199680-bf90-11eb-9145-a180addabbab.png)

↓这是向左滑动完两列后的效果

![image](https://user-images.githubusercontent.com/18142851/119913669-1184a180-bf91-11eb-9b01-59aef95d82fc.png)

请问能有什么办法能解决此问题嘛，我希望固定的两列能始终存在。

P.S. 阅读官方文档知道不推荐使用 `merge-cells` 合并单元格，然后就采用了 `span-method` ，发现还是不解决问题 

如果需要有mock数据能复现此bug，我后续可以提供~ 谢谢！

**Comment by DoloresY** [comment]
请问下这个问题解决了吗？我这也遇到这个问题了，请问您是怎么解决的啊？
