### ISSUE TITLE
ul-table 固定列 出现异常

### ISSUE THREAD

**Issue by ajc1996** [u-leo/umy-ui#66]
![image](https://user-images.githubusercontent.com/26572109/121515108-60194d80-ca1f-11eb-8462-e58d7590af2a.png)

**Comment by ajc1996** [comment]
知道了 之前是el-table 去掉el table的合计就好了

**Comment by lidaining-web** [comment]
> 知道了之前是el-table取消el table的恢复就好了

那不删除合计  咋处理呢

**Comment by lidaining-web** [comment]
> 知道了之前是el-table取消el table的恢复就好了

那不删除合计  咋处理呢
