### ISSUE TITLE
ux-table 动态新增列，新增的列位置显示不正常

### ISSUE THREAD

**Issue by Manybin** [u-leo/umy-ui#69]
ux-table-column 里 v-for="(item, index) in columns"
如果对columns手动新增列，新增加的列的位置显示不正常。
例如：columns= [a,b,c] 我在a后面增加一列是没有问题的，这时数组为[a,d,b,c]，我在b后面再增加一列，这时数组变成了[a,d,e,b,c];原因我在b增加时，获取b的下标还是最开始的1，b的下标没有更新。
这个问题可以帮忙看下怎么解决吗

**Comment by livelyPeng** [comment]
刷新表格试试

**Comment by livelyPeng** [comment]
刷新表格试试
