### ISSUE TITLE
There no license information in project

### ISSUE THREAD

**Issue by twister229** [u-leo/umy-ui#7]
Hi @livelyPeng ,
Could you please add license file to this project? Same with https://github.com/livelyPeng/pl-table/blob/master/LICENSE
Or is there any reason of this missing?
Thanks & Best regards,
Twister

**Comment by livelyPeng** [comment]
@twister229 ok,  it has been added！！！！！！

**Comment by twister229** [comment]
@livelyPeng thank you very much!
