### ISSUE TITLE
table组件未使用use-virtual  跟 row-height时,   调整列宽会有显示问题

### ISSUE THREAD

**Issue by Ghjsw** [u-leo/umy-ui#71]
![image](https://user-images.githubusercontent.com/20982392/122863631-b5c1f400-d355-11eb-88f0-205e94dcec8e.png)
如图,超出的文字不会隐藏,不会显示省略号,或者换行

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/multiLevelMeter  请看这个 ，无任何问题，不是有  虚拟的前提下

**Comment by Ghjsw** [comment]
> http://www.umyui.com/umycomponent/multiLevelMeter 请看这个 ，无任何问题，不是有 虚拟的前提下

在column 开启 
show-overflow-tooltip 属性后  就会出现,上面的例子  列会换行,并不会出现...
--


<br class="Apple-interchange-newline">

**Comment by livelyPeng** [comment]
那你在看看http://www.umyui.com/umycomponent/gudinglie 这个&nbsp; 去拖动那个 地址列 在看看会不会&nbsp; &nbsp; &nbsp;&nbsp;无任何问题，不是 虚拟的前提下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] table组件未使用use-virtual  跟 row-height时,   调整列宽会有显示问题 (#71)





  
http://www.umyui.com/umycomponent/multiLevelMeter 请看这个 ，无任何问题，不是有 虚拟的前提下
  
在column 开启
 show-overflow-tooltip 属性后  就会出现,上面的例子  列会换行,并不会出现...

**Comment by Ghjsw** [comment]
> http://www.umyui.com/umycomponent/gudinglie
从这里看 , 似乎是正常的

**Comment by livelyPeng** [comment]
see&nbsp; you&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] table组件未使用use-virtual  跟 row-height时,   调整列宽会有显示问题 (#71)





  
http://www.umyui.com/umycomponent/gudinglie
 从这里看 , 似乎是正常的
