### ISSUE TITLE
umy-table这个包可以开源吗?

### ISSUE THREAD

**Issue by xx732395** [u-leo/umy-ui#74]

**Comment by livelyPeng** [comment]
可以单独给你，不开源！

**Comment by xiaoxiao-lady** [comment]
同问，可以开源么，想要学习一下

**Comment by Observer-L** [comment]
> 可以单独给你，不开源！

同问，想要学习umy-table虚拟列表部门的实现。
怎么联系作者大大呢？

@livelyPeng

**Comment by w-joker** [comment]
> 可以单独给你，不开源！

大佬您好，可以发我一份吗？想学习一下

**Comment by zliuxia** [comment]
大佬，可以发我一份吗

**Comment by aehyok** [comment]
@livelyPeng 大佬可以分享发一份吗？455043818@qq.com 或者微信aehyok 
感谢大佬。

**Comment by joey127yao** [comment]
大佬,可以发一份给我吗？  joey.help@aliyun.com, 感谢大佬

**Comment by kaiyuanbaba** [comment]
@livelyPeng 大佬可以分享发一份吗？644460879@qq.com
感谢大佬。

**Comment by xd15332538931** [comment]
@livelyPeng  大佬可以给我发下 umy-table 这个包吗 想学习下 xd15332538931@163.com 感谢

**Comment by yq8023** [comment]
@livelyPeng 同问，想学习一下 umy-table 处理大数据下选择不卡顿的方案，2411041902@qq.com 感谢

**Comment by kaiyuanbaba** [comment]
scroll_X: {
&nbsp; &nbsp; &nbsp; type: Object,
&nbsp; &nbsp; &nbsp; default: () =&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; // gt: 0，代表永远开启虚拟， -1： 关闭虚拟， 60：代表行大于60行 开启虚拟， oSize: 1 代表可视区域额外渲染的条数
&nbsp; &nbsp; &nbsp; &nbsp; return { gt: 10, oSize: 0 };
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; },
&nbsp; &nbsp; scroll_Y: {
&nbsp; &nbsp; &nbsp; type: Object,
&nbsp; &nbsp; &nbsp; default: () =&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; return { gt: -1, oSize: 0 };
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; },




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "u-leo/umy-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [u-leo/umy-ui] umy-table这个包可以开源吗? (#74)





 
@livelyPeng 同问，想学习一下 umy-table ***@***.*** 感谢

**Comment by inooNgt** [comment]
大佬，可以发一份umy table源码吗，遇到问题需要修改，谢谢

**Comment by foriacus** [comment]
大佬，能发一份umy table源码吗？老项目用到了需要优化，感谢🙏 277854832@qq.com
