### ISSUE TITLE
希望能够支持按列编辑

### ISSUE THREAD

**Issue by Tilang** [u-leo/umy-ui#75]
虽然现在也可以自己通过自定义表头做到这个功能，但是还是希望能够官方支持一下。
功能描述：通过点击表头，可以将所有行/选中行的这一列切换到编辑状态，然后支持两种编辑方式：一，可以在表头处编辑，一次覆盖所有行。二，在单元格编辑

**Comment by livelyPeng** [comment]
...

**Comment by Tilang** [comment]
> ...

迎难而上啊，少年，相信你

**Comment by livelyPeng** [comment]
这个需求没时间哦，我告诉你怎么实现，首先1. 列不可以激活多行 多列！，   你就头部输入框输入了，直接改变data数据的单元格值，    如果你非要想那种感觉上是激活状态了，你看看 文档的编辑表格 全部显示那种感觉  去写写！
