### ISSUE TITLE
ux-grid的列 动态新增、删除、调整顺序操作后，表格的数据没有同步调整

### ISSUE THREAD

**Issue by pzl19930919** [u-leo/umy-ui#76]
ux-grid的列 动态新增、删除、调整顺序操作后，表格的数据没有同步调整
隐藏前：
![image](https://user-images.githubusercontent.com/24291180/125378851-0e6b3680-e3c2-11eb-97af-c523fe7d0f08.png)
隐藏后：
![image](https://user-images.githubusercontent.com/24291180/125378882-1aef8f00-e3c2-11eb-9b6e-e8ed2bd09fcd.png)

**Comment by pzl19930919** [comment]
调用refreshColumn或者doLayout都不管用，只有v-if重新渲染才行

**Comment by livelyPeng** [comment]
延迟下呢
调用呢

**Comment by pzl19930919** [comment]
延迟也不行

**Comment by livelyPeng** [comment]
你自己去看下文档的&nbsp; 表格列拖拽&nbsp; 实例吧&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月19日(星期一) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux-grid的列 动态新增、删除、调整顺序操作后，表格的数据没有同步调整 (#76)





 
延迟也不行

**Comment by pzl19930919** [comment]
另外我发现，如果父组件是dialog，show-overflow弹出层层级不够

**Comment by Wilburn-hub** [comment]
请问是怎么解决这个问题呢，我也遇到这个问题

**Comment by wenpengpeng** [comment]
> 调用refreshColumn或者doLayout都不管用，只有v-if重新渲染才行

本质上应该是你的ux-table-column节点绑定的key值不对引起的，我就是这样的，应该绑定一个数据源中的唯一属性作为key值，我就是绑定的v-for里面的index参数，这样就会引起跟你一样的数据错列的问题，我换成一个唯一属性值就正常了。
![image](https://user-images.githubusercontent.com/34331662/204071143-2048a6c3-4f7e-4c3c-a564-e4c96bdf798e.png)
像上图这样:key="index"就会引起数据错位，而换成类似:key="col.id"绑定一个唯一id就正常了
