### ISSUE TITLE
调用验证报错

### ISSUE THREAD

**Issue by ChaselCho** [u-leo/umy-ui#77]
错误内容:ReferenceError: regeneratorRuntime is not defined
    at a.validate (umy-table.common.js:1)
    at a.vaildSaveEvent (collectTaskDetail.vue?1484:626)
    at click (collectTaskDetail.vue?109a:641)
    at He (vue.min.js:6)
    at a.n (vue.min.js:6)
    at He (vue.min.js:6)
    at a.e.$emit (vue.min.js:6)
    at a.handleClick (index.min.js:5)
    at He (vue.min.js:6)
    at HTMLButtonElement.n (vue.min.js:6)
Ue @ vue.min.js:6
Be @ vue.min.js:6
Re @ vue.min.js:6
He @ vue.min.js:6
n @ vue.min.js:6
He @ vue.min.js:6
e.$emit @ vue.min.js:6
handleClick @ index.min.js:5
He @ vue.min.js:6
n @ vue.min.js:6
Yr.o._wrapper @ vue.min.js:6

  代码:
    <ux-table-column fixed="right" title="Operations" width="200">
      <template v-slot="{ row }">
        
        <template v-if="$refs.plxTable.isActiveByRow(row)">
          <el-button @click="vaildSaveEvent(row)" type="primary">Save</el-button>
          <el-button @click="cancelRowEvent(row)">Cancel</el-button>
        </template>
        <template v-else>
          <el-button @click="editRowEvent(row)">Edit</el-button>
        </template>
      </template>
    </ux-table-column>

vaildSaveEvent(row){
    this.$refs.plxTable.validate(row).then(data => {
                if (data) {
                }
                console.log(data)
            })
    },

![image](https://user-images.githubusercontent.com/39975272/125385783-08d50880-e350-11eb-84a8-cc6abfb196ce.png)

**Comment by livelyPeng** [comment]
文档报错吗？ 升级下版本呢
、
