### ISSUE TITLE
表格列设置为fixed:right时，显示异常

### ISSUE THREAD

**Issue by DtStorm** [u-leo/umy-ui#78]
正常情况下操作列是这样的
![image](https://user-images.githubusercontent.com/56500428/125877019-66a3074a-da8e-418d-a564-8cea212120f1.png)
当c操作列开启了fixed:right 后
![image](https://user-images.githubusercontent.com/56500428/125877061-3ba8a5ce-64c9-4492-ae6d-5279c8c89dc6.png)
操作列不显示了
![image](https://user-images.githubusercontent.com/56500428/125877085-43936f24-b537-4244-a323-a503786eb2c7.png)

**Comment by DtStorm** [comment]
补充： 是u-table 和 u-table-column

**Comment by livelyPeng** [comment]
亲爱的. 引入样式了嘛

**Comment by DtStorm** [comment]
果然如此，忘记加样式了，感谢
