### ISSUE TITLE
二次懒加载问题

### ISSUE THREAD

**Issue by LIHONGYUANYUAN** [u-leo/umy-ui#79]
虚拟滚动（reloadData加载数据）+懒加载，增加一条数据到数据库，怎么调用当前父节点从后端重新刷新一下数据呢

**Comment by livelyPeng** [comment]
在行上加个刷新按钮， 点击下发请求，然后请求回来的数据，自己插入到data里面，在设置表格数据，然后自己展开当前节点，  自己动动脑子！

**Comment by LIHONGYUANYUAN** [comment]
请求数据没问题，怎么设置表格数据reloaddata吗，那又回到根目录了啊，，展开当前节点的那个方法只有之前展开过才有效，。没有调用懒加载重新设置表格数据的方法啊，或者有只刷新当前节点的 表格数据 的方法 吗？也行

**Comment by livelyPeng** [comment]
你要是会vue 也不会问这个问题， 刷新当前节点，如果是一个遍历改变了会刷新当前，  但是如果是个数组， 数组元素变化了，代表整个节点都会刷新，key都会变化， 看过vue “”以下不会触发视图的更新。“”这个文章过吗？   你为毛去纠结当前节点刷新， 你TM直接吧数据 给表格对应的索引下 就完了，你管这么多！ 操作数组会吗？  来加载成功了，你告诉我 重新来加载？ 那不就等于你去刷新数据？

**Comment by livelyPeng** [comment]
你要是会vue 也不会问这个问题， 刷新当前节点，如果是一个变量改变了会刷新当前，  但是如果是个数组， 数组元素变化了，代表整个节点都会刷新，key都会变化， 看过vue “”以下不会触发视图的更新。“”这个文章过吗？   你为毛去纠结当前节点刷新， 你TM直接吧数据 给表格对应的索引下 就完了，你管这么多！ 操作数组会吗？  来加载成功了，你告诉我 重新来加载？ 那不就等于你去刷新数据？

**Comment by LIHONGYUANYUAN** [comment]
楼主能不能把嘴里的零碎去掉，一句也没说到点上。。。

**Comment by livelyPeng** [comment]
在行上加个刷新按钮， 点击下发请求，然后请求回来的数据，自己插入到data里面，在设置表格数据，然后自己展开当前节点，“”“”“那又回到根目录了啊” 那么会不会自己在展开，如果还有问题，请看ux的树表格！

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/virtualTreeTableAddNode  跟这个有啥区别，都是往节点添加数据，真的是有毒了！
