### ISSUE TITLE
ux 的summary-method 里不能返回html吗

### ISSUE THREAD

**Issue by ajc1996** [u-leo/umy-ui#81]
u table 的summary-method 中二维数组里返回html是有效的 换成ux好像不行？

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/126112808-c9535d5c-df6c-4daa-942b-7d7d3cbcc272.png)

**Comment by livelyPeng** [comment]
ux  有 
<html>
<body>


footer | 自定义表尾内容的模板 | 如template上写 v-slot:footer="scope" | — | {column, columnIndex, $columnIndex, _columnIndex, $rowIndex, items}
-- | -- | -- | -- | --



</body>
</html>

**Comment by ajc1996** [comment]
希望后期文档里能补充一下 我好像没看见

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/ux-table-column-api

Scoped Slot
插槽






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月19日(星期一) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux 的summary-method 里不能返回html吗 (#81)





 
希望后期文档里能补充一下 我好像没看见

**Comment by ajc1996** [comment]
看到了 感谢
