### ISSUE TITLE
utable 开启虚拟滚动的同时 把某一列fixed:right 表格没对齐

### ISSUE THREAD

**Issue by DtStorm** [u-leo/umy-ui#82]
![image](https://user-images.githubusercontent.com/56500428/126620764-8ab1c78a-2806-4aa3-9d19-399aebf8a871.png)
确认已经引入了样式

**Comment by livelyPeng** [comment]
https://github.com/u-leo/umy-ui/issues/32  多去找找提问   看看有没有类似的 提问

**Comment by livelyPeng** [comment]
逗比
