### ISSUE TITLE
checkbox固定，设置最大高度，行滚到一半时选择复选框，固定栏高度问题

### ISSUE THREAD

**Issue by zhang5707** [u-leo/umy-ui#86]
- [ ]

**Comment by zhang5707** [comment]
![11](https://user-images.githubusercontent.com/33337464/127595417-05b25f37-20fe-41e5-b821-ccb16ee37a4e.png)
![22](https://user-images.githubusercontent.com/33337464/127595425-b7598559-4814-4c41-9cd3-1bfe0397f361.png)

**Comment by livelyPeng** [comment]
set the height, no max height

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/virtualCheckboxTable
