### ISSUE TITLE
树形表格有上移下移的功能吗

### ISSUE THREAD

**Issue by zliuxia** [u-leo/umy-ui#87]
树形表格有上移下移的功能吗

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/filterFields

**Comment by zliuxia** [comment]
是表格每一行数据的上移下移

**Comment by livelyPeng** [comment]
那个不是吗？表格弹窗里面。。你想在每行上面搞上下移动 自己写啊， 百度下，交换数组元素的位置， 百度下 数组怎么上下移动排序？
