### ISSUE TITLE
ux-grid列比较多开启横向虚拟加载时，未加载的dom对应数据校验失败不会给出提示

### ISSUE THREAD

**Issue by xiaoxiaofei2016** [u-leo/umy-ui#91]
**ux-grid**设置了属性：valid-config: {autoPos: true}
**ux-table-column**设置了属性：editRender : { autofocus: '.el-input__inner' }
当列比较多，且有对应的校验规则，当表格此时横向滚动条在第一列的位置，如果第20列没有在可视区域，则第20列的校验失败了也不会自动聚焦，也没有任何提示

**Comment by livelyPeng** [comment]
这个问题呢 非常的好，但是没得办法哈，不可以实现，自己去获取当前可视区的表格数据，自己判断校验，自己给提示。

**Comment by livelyPeng** [comment]
1. 未加载的dom不可能聚焦，要想自己没问题，自己手懂关闭虚拟滚动，那么带来的就说卡。
2.  点击校验按钮，自己去获取当前可视区的表格数据，自己判断校验，自己给提示。
3.  否则自己关闭X轴虚拟滚动。属性： scrollY: {type: Object, default: () => { return {gt: 0, oSize: 0} }},
        scrollX: {type: Object, default: () => { return {gt: 0, oSize: 0} }},
scrollY: { gt: 0，代表永远开启虚拟， -1： 关闭虚拟， 60：代表行大于60行 开启虚拟，  }  
scrollX一样的道理不在描述。  你可以尝试： 把X轴写为你列的数量，就是关闭虚拟，但是自己看卡不卡！
4. 除了以上办法 没有任何办法！
5. 希望你不要关闭这个问题。为后面同学观看！

**Comment by xiaoxiaofei2016** [comment]
感谢作者，我把X轴虚拟关闭了

**Comment by xiaoxiaofei2016** [comment]
大佬，方便给个u-table的源码吗

**Comment by livelyPeng** [comment]
加群联系umyui机器人，私发

**Comment by xiaoxiaofei2016** [comment]
大佬好，qq申请加你好友几天了哦，你好像没有回应
