### ISSUE TITLE
合计行自动计算的时候，会出现小数位数问题

### ISSUE THREAD

**Issue by shengxq** [u-leo/umy-ui#94]
比如数据第一行 0.1   第二行  0.2
表格设置  show-summary
自动计算并显示合计数  0.30000000000000004
这个时候就只能自己写 计算合计的方法了
umy-ui 中提供 total-option  属性  这个 能不能增加一个 格式化参数 或者回调

**Comment by livelyPeng** [comment]
你自己都说了 ： “这个时候就只能自己写 计算合计的方法了”   那你为啥不做呢？

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/130209487-34b284f0-890a-4438-805d-a7c0b8728bab.png)
自己去写OK？ 什么时候需要教学JS拉？那人家需要 保留5位，3位  我难道给她搞个配置?

**Comment by shengxq** [comment]
不知道提供total-option参数功能的目的是什么，比如单位功能，是为了不用写合计函数吗？比如0.1+0.2合计由于浮点精度问题会出现小数位数很多的情况，如果想做，可以做个判断，修复合计精度问题感谢开源，只是建议发自我的华为手机-------- 原始邮件 --------发件人： livelyPeng ***@***.***>日期： 2021年8月20日周五 傍晚5:06收件人： u-leo/umy-ui ***@***.***>抄送： shengxq ***@***.***>, Author ***@***.***>主    题： Re: [u-leo/umy-ui] 合计行自动计算的时候，会出现小数位数问题 (#94)



自己去写OK？ 什么时候需要教学JS拉？那人家需要 保留5位，3位  我难道给她搞个配置?
