### ISSUE TITLE
表格中加el-switch，滚动会来回闪烁

### ISSUE THREAD

**Issue by JackFan90** [u-leo/umy-ui#97]
![image](https://user-images.githubusercontent.com/58178594/131062752-b18a81c7-ad5f-4fd7-8795-90011238f74c.png)
鼠标滚轮滚动闪烁比较厉害，是重新渲染的问题吗？有没有什么解决办法？

**Comment by JackFan90** [comment]
打了这么多字不都是废话么？你不累吗？我问这个问题，自然是我水平有限，还多动脑想？装什么装？

**Comment by livelyPeng** [comment]
水平有限  所以你才不要装，弱鸡问题！问下你们老大！

**Comment by JackFan90** [comment]
后端程序员，过来问个前端小白的问题，还被咬，我也是醉了。就这还搞开源？还不让人问了？你是真的行！

**Comment by JackFan90** [comment]
辣鸡东西，不用就好

**Comment by livelyPeng** [comment]
后台 搞什么前端？公司这么菜？前端这么好学哇？开源是开源，问菜鸡问题，证明就是菜，你不适合搞前端！
