### ISSUE TITLE
use-virtual 开启时，在单元格编辑data的数据时，会回到首行

### ISSUE THREAD

**Issue by Hisioni** [u-leo/umy-ui#98]
<u-table
      ref="table"
      v-loading="loading"
      :data="tableData"
      border
      height="600px"
      use-virtual
      :span-method="handlerSpanMethod"
      :cell-class-name="handlerCellClass"
      style="width: 100%"
      :row-class-name="tableRowClassName"
      @cell-click="tabClick"
      @row-click="rowClick"
    >
      <el-table-column prop="id" label="序号" type="index" width="80" header-align="center" align="center" />
      <el-table-column prop="contentAndStandard" label="检查内容与评分标准" header-align="center" />
      <el-table-column prop="standardScore" label="标准分" width="80" align="center" />
      <el-table-column prop="demeritScore" label="扣分" width="120" align="center">
        <template v-slot="scope">
          <template v-if="view">{{ scope.row.demeritScore }}</template>
          <template v-else>
            <el-input-number
              v-if="scope.row.index === tabClickIndex && tabClickProp === 'demeritScore'"
              v-model="scope.row.demeritScore"
              :min="0"
              :max="scope.row.standardScore"
              controls-position="right"
              style="width: 100%;"
              @blur="inputBlur"
            />
            <span v-else>{{ scope.row.demeritScore }}</span>
          </template>
        </template>
      </el-table-column>
      <el-table-column prop="demeritContent" label="扣分原因" width="200" header-align="center">
        <template v-slot="scope">
          <template v-if="view">{{ scope.row.demeritContent }}</template>
          <template v-else>
            <el-input
              v-if="scope.row.index === tabClickIndex && tabClickProp === 'demeritContent'"
              type="textarea"
              v-model="scope.row.demeritContent"
              :rows="1"
              :autosize="{ minRows: 1, maxRows: 3 }"
              style="width: 100%;"
              @blur="inputBlur"
            />
            <span v-else>{{ scope.row.demeritContent }}</span>
          </template>
        </template>
      </el-table-column>
    </u-table>

---
```
只要更改了data的item的属性值，u-table就会重新渲染，回到首行，请问有好的解决方案吗？
```

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/131281960-9795c117-4f62-486b-a170-1d999d7a1c3e.png)

**Comment by Hisioni** [comment]
感谢！
